### ISSUE TITLE
Getting Unexpected Token issue on run

### ISSUE THREAD

**Issue by robschwartz** [NotLuksus/nft-art-generator#21]
Just installed the project and ran `nft-generate` but seeing the error below
```
/usr/local/lib/node_modules/nft-art-generator/node_modules/ora/index.js:401
		} catch {
		        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/nft-art-generator/bin/index.js:9:13)
```
I'm running the script from the `/nftg` folder and the structure of images matches what is expected
![image](https://user-images.githubusercontent.com/7434398/133996186-1d23c1dd-66e1-471c-a6e9-6c219da2c977.png)

Any suggestions on how to fix?

**Comment by robschwartz** [comment]
I updated my filenames to 
![image](https://user-images.githubusercontent.com/7434398/133997238-eeba30dc-3531-451e-bf62-e624494a0b96.png)
and still seeing the same issue
