### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Couldn't load image

### ISSUE THREAD

**Issue by oswinbk** [NotLuksus/nft-art-generator#24]
![cmd_TC31jGqxzk](https://user-images.githubusercontent.com/48634784/134847797-78ef08fb-b9de-4a2c-8c19-93c4154dac6c.png)

this error pops up every time I attempt to generate metadata.

**Comment by Ferydoni** [comment]
i get the exact same error.

**Comment by Julian2leiria** [comment]
Same error too, after generate thr NFT... "Couldn't load image" then the Metadata file don't generate...
With 2 files it's ok but with 2000 or 10000... nop...

**Comment by Julian2leiria** [comment]
" Known issues:
 Some special characters may resolve in some "File couldnt be loaded" errors. Try to remove any special characters from your file paths to resolve "...

**Comment by yrik** [comment]
```
⠹ Generating images/Users/yura/.nvm/versions/node/v16.8.0/lib/node_modules/nft-art-generator/node_modules/merge-images/dist/index.umd.js:39
			img.onerror = function () { return reject(new Error('Couldn\'t load image: ' + source + ', ' + JSON.stringify(sources))); };
			                                          ^

Error: Couldn't load image: [object Object], ["/Users/yura/cryptosnailsart/images/1-body/snailsalat.png","/Users/yura/cryptosnailsart/images/2-shell/undefined","/Users/yura/cryptosnailsart/images/3-vip/king.png","/Users/yura/cryptosnailsart/images/4-eyes/simple.png","/Users/yura/cryptosnailsart/images/5-emotion/crazysmile.png"]
    at img.onerror (/Users/yura/.nvm/versions/node/v16.8.0/lib/node_modules/nft-art-generator/node_modules/merge-images/dist/index.umd.js:39:46)
    at Image.<anonymous> (<anonymous>)
    at setSource (/Users/yura/.nvm/versions/node/v16.8.0/lib/node_modules/nft-art-generator/node_modules/canvas/lib/image.js:91:13)
    at Image.set (/Users/yura/.nvm/versions/node/v16.8.0/lib/node_modules/nft-art-generator/node_modules/canvas/lib/image.js:62:9)
    at /Users/yura/.nvm/versions/node/v16.8.0/lib/node_modules/nft-art-generator/node_modules/merge-images/dist/index.umd.js:41:12
    at new Promise (<anonymous>)
    at /Users/yura/.nvm/versions/node/v16.8.0/lib/node_modules/nft-art-generator/node_modules/merge-images/dist/index.umd.js:30:55
    at Array.map (<anonymous>)
    at /Users/yura/.nvm/versions/node/v16.8.0/lib/node_modules/nft-art-generator/node_modules/merge-images/dist/index.umd.js:30:24
```

**Comment by yrik** [comment]
for me it fails on 9996

**Comment by kleozzy** [comment]
Tried no spaces , no tags nothing I still get the couldn't load images error
