### ISSUE TITLE
It throws an error that it could not load the images

### ISSUE THREAD

**Issue by CecoSvidovski** [NotLuksus/nft-art-generator#35]
It asks me about each folder and file correctly and everything looks normal until it starts generating and then this error occurs 
`Error: Couldn't load image
    at img.onerror (C:\Users\user\OneDrive\Documents\nft generator\nft-art-generator-main\node_modules\merge-images\dist\index.umd.js:39:46)
    at setSource (C:\Users\user\OneDrive\Documents\nft generator\nft-art-generator-main\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\user\OneDrive\Documents\nft generator\nft-art-generator-main\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\user\OneDrive\Documents\nft generator\nft-art-generator-main\node_modules\merge-images\dist\index.umd.js:41:12
    at new Promise (<anonymous>)
    at C:\Users\user\OneDrive\Documents\nft generator\nft-art-generator-main\node_modules\merge-images\dist\index.umd.js:30:55
    at Array.map (<anonymous>)
    at C:\Users\user\OneDrive\Documents\nft generator\nft-art-generator-main\node_modules\merge-images\dist\index.umd.js:30:24
    at new Promise (<anonymous>)
    at mergeImages (C:\Users\user\OneDrive\Documents\nft generator\nft-art-generator-main\node_modules\merge-images\dist\index.umd.js:22:10)`

**Comment by nickgag626** [comment]
Resolved for me by rerunning 

npm init
npm install

**Comment by NotLuksus** [comment]
Try removing all spaces from your file path
